### ISSUE TITLE
Gluster disk check may alert unnessisarily

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/openshift-tools#13]
Since CNS can have multiple devices, one may be full while the other has lots of free space. This may cause alerts when everything is actually fine. Need to find a better metric for "gluster is full".

https://github.com/BCDevOps/openshift-tools/blob/master/utils/ansible-playbooks/deploy-monitoring/templates/ocp-monitor.j2

**Comment by jefkel** [comment]
Closed, moved to bcgov-c private repository
see commit: https://github.com/BCDevOps/openshift-tools/commit/46f9f851711e141ecce7d31b8699d58e9cee091d
