### ISSUE TITLE
Hardcoded router count causes manual updates to the playbook

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/openshift-tools#30]
https://github.com/BCDevOps/openshift-tools/blob/master/utils/ansible-playbooks/docker-log-change/roles/docker-config/tasks/uncordon.yml#L19

Pre drain  (on infras only) we should collect the current # or expected running pods and; 
- bail if not all pods are running already
- set the fact and compare against it in the uncordon task

**Comment by jefkel** [comment]
Closing, affected playbook has been migrated to bcgov-c to be managed by DXC
See commit: https://github.com/BCDevOps/openshift-tools/commit/46f9f851711e141ecce7d31b8699d58e9cee091d
