### ISSUE TITLE
improve infrastructure checking in reboot playbook

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/openshift-tools#5]
need to enhance the checks in uncordon.yml; 
- add checks for ipfw
- account for nodes not running routers / etc. 
- possibly check for registry pods as well
- check for ready status of pods, not just running

**Comment by jefkel** [comment]
moved to bcgov-c, see commit: https://github.com/BCDevOps/openshift-tools/commit/46f9f851711e141ecce7d31b8699d58e9cee091d
