### ISSUE TITLE
Going through "Update Registration Profile" flow after registering, prior to confirming email skips to "thank you" and does not show profile info.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/openshift-tools#58]
Steps to recreate:
- Complete registration, but don't confirm email, (should be on "thank you" page)
- In the same browser session, click the "home" button (should see "Update Registration Profile" button.)
- Click  "Update Registration Profile". (you'll see the "Thank You" page)

Expected behaviour is to see the profile form and allow updates to it.

Appears to be a client state issue, as reloading page resolves the problem and the correct flow is executed.

**Comment by ShellyXueHan** [comment]
So for now, if user go back to home and click on "Update Registration Profile" button, they will see the form again.
However, there is no persist storage with the app, refresh will loss all the states. Issues created for this.
