### ISSUE TITLE
Do we want the "end user" name to be "Reggie"?

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/openshift-tools#59]

**Comment by ShellyXueHan** [comment]
@sheaphillips any ideas of naming it?

**Comment by sheaphillips** [comment]
"Official"/full name should probably be something like "Developer Program Registration and Onboarding Tool". 

I'll give this some more thought.

**Comment by lukegonis** [comment]
This is Blocked until @sheaphillips gives it more thought.

**Comment by ShellyXueHan** [comment]
@sheaphillips How about `Pathfinder Rocket.Chat Invitation App`?

**Comment by sheaphillips** [comment]
sure.
