### ISSUE TITLE
"Welcome" message should use Firstname as provided in profile form.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/openshift-tools#62]
Looks like the IDIR-provided name is being used on the welcome screen, instead of (expected) the Firstname I provided when registering.

**Comment by ShellyXueHan** [comment]
This looks like a feature in test and prod SSO, that whenever IDIR user logged in, it updates the user's firstName to the format as the fullName+department...so the payload from keycloak query is ```[ { id: 'xx',
    createdTimestamp: 1540924169987,
    username: 'idir\\shellhan',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'Han, Shelly CITZ:EX',
    lastName: 'Han',
    email: 'shelly.han@gov.bc.ca',
    attributes: { idir_userid: [Array], displayName: [Array] },
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access:
     { manageGroupMembership: true,
       view: true,
       mapRoles: true,
       impersonate: true,
       manage: true } } ]```
