### ISSUE TITLE
Email address not passed through from GitHub auth in registration flow?

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/openshift-tools#65]
When registering (from an invite) and logging in with GitHub as part of process, the registration form does picks up my first name and last name (from GitHub presumably) but shows a blank email.  Perhaps the "scope" is not set properly on the GitHub OAuth config?

**Comment by ShellyXueHan** [comment]
The case might be that the Github account has a private email, so sso is not able to fetch it. That's part of the reason for re-enforcing user to enter email and check. Closing.
