### ISSUE TITLE
Update OpenShift Project Labels to include PO and PL rocket-chat contact information.

### ISSUE THREAD

**Issue by caggles** [BCDevOps/openshift-tools#81]
update the template for requesting new projects
update the playbook to reflect the new fields

**Comment by ShellyXueHan** [comment]
https://github.com/BCDevOps/openshift-tools/pull/82
https://github.com/BCDevOps/openshift-tools/pull/82

**Comment by ShellyXueHan** [comment]
@caggles the two tasks mentioned in this ticket has been completed. The work to update the existing projects should be captured by another issue. Closing this one.
